server:
  port: 18082
spring:
  application:
    name: changgou-canal
  jooq:
    sql-dialect: mysql
  flyway:
    baseline-on-migrate: true
  redis:
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: -1ms
        min-idle: 3
    timeout: 6000ms
    password: 123456
    cluster:
      nodes: www.brick.com:9001,www.brick.com:9003,www.brick.com:9005,www.brick.com:9002,www.brick.com:9004,www.brick.com:9006
      max-redirects: 3
eureka:
  client:
    service-url:
      defaultZone: http://www.brick.com:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info,health
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
#canal配置
canal:
  # 账号  canal-admin application.yml 设置的
  username: canal
  # 密码
  password: canal
  server: www.brick.com:11111
  destination: example
info:
  app:
    name: changgou-canal
    version: v1.0.0
    description: this is a canal microservices