spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  application:
    name: changgou_file
server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.18:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
# MinIO对象存储相关配置.
minio:
  endpoint: http://192.168.3.18:9090 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
