spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: changgou_file
server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.18:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true