server:
  port: 18088
spring:
  thymeleaf:
    cache: false
  application:
    name: search-web
eureka:
  client:
    service-url:
      defaultZone: http://www.brick.com:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
management:
  endpoints:
    web:
      exposure:
        include: info,health
info:
  app:
    name: search-web
    version: v1.0.0
    description: this is a search-web microservices
