server:
  port: 7001
eureka:
  instance:
    hostname: 192.168.3.18
  client:
    register-with-eureka: false #是否将自己注册
    fetch-registry: false #是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: changgou_eureka