server:
  port: 18086
spring:
  application:
    name: changgou-search
  data:
    elasticsearch:
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://www.brick.com:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  hystrix:
    enabled: true
#超时配置
#ribbon:
  #ReadTimeout: 60000
  #ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
management:
  health:
    redis:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health
      cors:
        allow-credentials:
info:
  app:
    name: changgou-search
    version: v1.0.0
    description: this is a search microservices

elasticsearch:
  addr: www.brick.com:9200
  connectTimeout: 60000
  socketTimeout: 60000