server:
  port: 18086
spring:
  application:
    name: changgou-search
  data:
    elasticsearch:
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  hystrix:
    enabled: true
#超时配置
#ribbon:
  #ReadTimeout: 60000
  #ConnectTimeout: 60000
management:
  endpoints:
    web:
      exposure:
        include: info,health
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
elasticsearch:
  addr: 192.168.3.18:9200