server:
  port: 18081
info:
  app:
    name: changgou-goods
    version: v1.0.0
    description: this is a goods microservices
spring:
  application:
    name: changgou-goods
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.brick.com:3306/changgou_goods?serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
    druid:
      initial-size: 5 #初始化时建立物理连接的个数
      min-idle: 5 #最小连接池数量
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: true #是否缓存preparedStatement,mysql5.5+建议开启
      filters: stat,wall #配置扩展插件
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
eureka:
  client:
    service‐url:
      defaultZone: http://www.brick.com:7001/eureka
  instance:
    prefer‐ip‐address: true
management:
  endpoints:
    web:
      exposure:
        include: info,health
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.changgou.goods.pojo
pagehelper:
  helper-dialect: mysql
  reasonable: true
seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      changgou-goods-group: default
  registry:
    type: eureka
    eureka:
      application: default
      service-url: http://www.brick.com:7001/eureka
      weight: 1