spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  application:
    name: changgou-file
server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://www.brick.com:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info,health
# MinIO对象存储相关配置.
minio:
  endpoint: http://www.brick.com:9090 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
info:
  app:
    name: changgou-file
    version: v1.0.0
    description: this is a file microservices
