server:
  port: 18090
info:
  app:
    name: changgou-order
    version: v1.0.0
    description: this is a order microservices
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: changgou-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.brick.com:3306/changgou_goods?serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
    druid:
      initial-size: 5 #初始化时建立物理连接的个数
      min-idle: 5 #最小连接池数量
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: true #是否缓存preparedStatement,mysql5.5+建议开启
      filters: stat,wall #配置扩展插件
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #引入redis
  redis:
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: -1ms
        min-idle: 3
    timeout: 6000ms
    password: 123456
    cluster:
      nodes: www.brick.com:9001,www.brick.com:9003,www.brick.com:9005,www.brick.com:9002,www.brick.com:9004,www.brick.com:9006
      max-redirects: 3
eureka:
  client:
    service‐url:
      defaultZone: http://www.brick.com:7001/eureka
  instance:
    prefer‐ip‐address: true
management:
  endpoints:
    web:
      exposure:
        include: info,health
feign:
  hystrix:
    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.changgou.order.pojo
pagehelper:
  helper-dialect: mysql
  reasonable: true